# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-19 14:09
from __future__ import unicode_literals

import commons.core
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0006_auto_20170319_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_url', models.CharField(max_length=1024, verbose_name='Ссылка на запись')),
                ('title', models.CharField(max_length=1024, verbose_name='название')),
                ('published', models.BooleanField(default=False)),
                ('date_published', models.DateTimeField(auto_now=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to=commons.core.UploadTo('records'), verbose_name='обложка')),
                ('dj', models.ManyToManyField(default=None, to='blog.Author', verbose_name='DJ')),
                ('tag', models.ManyToManyField(to='blog.Tag', verbose_name='теги')),
            ],
            options={
                'verbose_name': 'Запись эфира',
                'verbose_name_plural': 'Записи эфиров',
            },
            managers=[
                ('published_items', django.db.models.manager.Manager()),
            ],
        ),
    ]
