# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-07 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='published',
            field=models.BooleanField(default=False, verbose_name='активен'),
        ),
        migrations.AlterField(
            model_name='records',
            name='record_url',
            field=models.CharField(max_length=1024, verbose_name='ссылка на запись'),
        ),
    ]
