# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-08 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20170507_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='record_date',
            field=models.DateTimeField(default='2017-01-01'),
        ),
    ]
