# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-08 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_records_record_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='stick_on_main',
            field=models.BooleanField(default=False, verbose_name='закреплен на главной'),
        ),
        migrations.AlterField(
            model_name='records',
            name='record_date',
            field=models.DateTimeField(default='2017-01-01', verbose_name='дата эфира'),
        ),
    ]
