# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-09 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20170508_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composer', models.CharField(max_length=1024, verbose_name='исполнитель')),
                ('song', models.CharField(max_length=1024, verbose_name='песня')),
            ],
        ),
        migrations.AddField(
            model_name='records',
            name='track',
            field=models.ManyToManyField(to='records.Track', verbose_name='треки'),
        ),
    ]
