# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-09 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20170509_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='records',
            options={'verbose_name': 'запись эфира', 'verbose_name_plural': 'записи эфиров'},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'verbose_name': 'композиция', 'verbose_name_plural': 'композиции'},
        ),
    ]
