# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-19 08:19
from __future__ import unicode_literals

import commons.core
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoAlbumTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=511, verbose_name='наименование (альбома или фото)')),
                ('photo', models.ImageField(upload_to=commons.core.UploadTo('photo'), verbose_name='фото')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='просмотры')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='photo.PhotoAlbumTree', verbose_name='раздел')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
