# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-19 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20170219_0848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photoalbumtree',
            options={'verbose_name': 'галерея', 'verbose_name_plural': 'галереи'},
        ),
    ]
