# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-28 07:03
from __future__ import unicode_literals

import commons.core
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('video_url', models.CharField(max_length=10240, verbose_name='ссылка на видео файл')),
                ('date_published', models.DateTimeField(verbose_name='дата публикации')),
                ('published', models.BooleanField(default=False, verbose_name='опубликован')),
                ('position', models.IntegerField(db_index=True, default=500, verbose_name='позиция')),
                ('hits', models.PositiveIntegerField(db_index=True, default=0, verbose_name='просмотры')),
                ('pic', models.ImageField(blank=True, null=True, upload_to=commons.core.UploadTo('blog'), verbose_name='превью видео')),
            ],
            options={
                'verbose_name': 'видео',
                'verbose_name_plural': 'видео',
            },
        ),
    ]
