# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-29 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='video',
            managers=[
                ('published_items', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='location',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='место съемки'),
        ),
        migrations.AlterField(
            model_name='video',
            name='hits',
            field=models.PositiveIntegerField(default=0, verbose_name='просмотры'),
        ),
    ]
