# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-30 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20170529_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='location',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_url',
        ),
        migrations.AddField(
            model_name='video',
            name='video_url_mp4',
            field=models.CharField(max_length=10240, null=True, verbose_name='ссылка на mp4 видео файл'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_url_webm',
            field=models.CharField(max_length=10240, null=True, verbose_name='ссылка на webm видео файл'),
        ),
        migrations.AlterField(
            model_name='video',
            name='hits',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='просмотры'),
        ),
    ]
