# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-14 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('target', models.CharField(choices=[('_self', '_self (default)'), ('_blank', '_blank'), ('_parent', '_parent'), ('_top', '_top')], default='', max_length=255, verbose_name='аттрибут target')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.TopMenu', verbose_name='раздел')),
            ],
            options={
                'verbose_name': 'пункт главного меню',
                'verbose_name_plural': 'пункты главного меню',
            },
        ),
    ]
