# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-15 14:14
from __future__ import unicode_literals

import commons.core
from django.db import migrations, models
import django.db.models.deletion
import tinymce_4.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=511, verbose_name='имя')),
                ('pic', models.ImageField(upload_to=commons.core.UploadTo('page'), verbose_name='аватар')),
                ('description', models.CharField(max_length=2047, verbose_name='описание')),
            ],
            options={
                'verbose_name_plural': 'авторы',
                'verbose_name': 'автор',
            },
        ),
        migrations.CreateModel(
            name='BlogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('date_published', models.DateTimeField(verbose_name='дата публикации')),
                ('published', models.BooleanField(default=False, verbose_name='опубликован')),
                ('pic', models.ImageField(blank=True, null=True, upload_to=commons.core.UploadTo('blog'), verbose_name='изображение')),
                ('content', tinymce_4.fields.TinyMCEModelField(blank=True, verbose_name='содержимое')),
                ('position', models.IntegerField(db_index=True, default=500, verbose_name='позиция')),
                ('hits', models.PositiveIntegerField(db_index=True, default=0, verbose_name='просмотры')),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='blog_creator', to='blog.Author', verbose_name='автор')),
            ],
            options={
                'verbose_name_plural': 'топики',
                'verbose_name': 'топик',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Тег')),
            ],
            options={
                'verbose_name_plural': 'теги',
                'verbose_name': 'тег',
            },
        ),
    ]
