# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-21 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager
import tinymce_4.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_author_blogitem_tag'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blogitem',
            managers=[
                ('published_items', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='blogitem',
            name='preview',
            field=models.TextField(default=None, null=True, verbose_name='превью'),
        ),
        migrations.AlterField(
            model_name='blogitem',
            name='content',
            field=tinymce_4.fields.TinyMCEModelField(blank=True, verbose_name='текст поста'),
        ),
    ]
