# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-19 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170121_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogitem',
            name='topic_type',
            field=models.IntegerField(choices=[(0, 'Топик в блоге'), (1, 'Событие'), (2, 'Запись эфира')], default=0),
        ),
    ]
