# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-19 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogitem_topic_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='topmenu',
            name='order',
            field=models.IntegerField(default=10, verbose_name='сортировка'),
        ),
        migrations.AlterField(
            model_name='blogitem',
            name='topic_type',
            field=models.IntegerField(choices=[(0, 'Топик в блоге'), (1, 'Событие'), (2, 'Запись эфира')], default=0, verbose_name='тип записи'),
        ),
    ]
