# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-07 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_adv'),
    ]

    operations = [
        migrations.AddField(
            model_name='adv',
            name='adv_order',
            field=models.IntegerField(default=500, verbose_name='сортировка'),
        ),
        migrations.AddField(
            model_name='adv',
            name='adv_position',
            field=models.IntegerField(choices=[(0, 'в шапке'), (1, 'в сайдбаре')], default=0, verbose_name='позиция баннера'),
        ),
    ]
