# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-07 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170507_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adv',
            name='event_location',
            field=models.CharField(max_length=32, verbose_name='место события'),
        ),
        migrations.AlterField(
            model_name='adv',
            name='event_week_day',
            field=models.CharField(max_length=32, verbose_name='день недели'),
        ),
    ]
