# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-07 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170507_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='adv',
            name='link',
            field=models.CharField(default=None, max_length=32, null=True, verbose_name='ссылка'),
        ),
    ]
