# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-08 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_adv_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adv',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='adv',
            name='event_location',
        ),
        migrations.RemoveField(
            model_name='adv',
            name='event_week_day',
        ),
        migrations.AddField(
            model_name='adv',
            name='additional',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='дополнительно'),
        ),
        migrations.AddField(
            model_name='adv',
            name='description',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='adv',
            name='title',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='adv',
            name='adv_position',
            field=models.IntegerField(choices=[(0, 'в шапке'), (1, 'слайдер на главной')], default=0, verbose_name='позиция баннера'),
        ),
    ]
