# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-08 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20170508_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogitem',
            name='stick_on_main',
            field=models.BooleanField(default=False, verbose_name='закреплен на главной'),
        ),
    ]
