# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-09 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_blogitem_stick_on_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adv',
            name='adv_position',
            field=models.IntegerField(choices=[(0, 'в шапке'), (1, 'слайдер на главной'), (2, 'событие в сайдбаре')], default=0, verbose_name='позиция баннера'),
        ),
    ]
